// ============================================================
// dict.js — Dicționar central English Zero→Hero
// Importat de: vocabulary.html, grammar.html, slot machines
// ============================================================

const DICT_WORDS = [

  // PRONUME
  {en:'I',    ro:'Eu',     ph:'AI',    e:'🙋', cat:'pronume'},
  {en:'You',  ro:'Tu',     ph:'IU',    e:'👤', cat:'pronume'},
  {en:'He',   ro:'El',     ph:'HI',    e:'👨', cat:'pronume'},
  {en:'She',  ro:'Ea',     ph:'ȘI',    e:'👩', cat:'pronume'},
  {en:'It',   ro:'El/Ea',  ph:'IT',    e:'🤖', cat:'pronume'},
  {en:'We',   ro:'Noi',    ph:'UII',   e:'👥', cat:'pronume'},
  {en:'They', ro:'Ei/Ele', ph:'ĐEI',  e:'👫', cat:'pronume'},

  // VERBE
  {en:'be',     ro:'a fi',       ph:'BII',     e:'⭐', cat:'verb'},
  {en:'have',   ro:'a avea',     ph:'HEV',     e:'🤲', cat:'verb'},
  {en:'do',     ro:'a face',     ph:'DUU',     e:'🔧', cat:'verb'},
  {en:'say',    ro:'a spune',    ph:'SEI',     e:'💬', cat:'verb'},
  {en:'go',     ro:'a merge',    ph:'GOU',     e:'🚶', cat:'verb'},
  {en:'get',    ro:'a obține',   ph:'GET',     e:'📥', cat:'verb'},
  {en:'make',   ro:'a crea',     ph:'MEIK',    e:'🛠️', cat:'verb'},
  {en:'know',   ro:'a ști',      ph:'NOU',     e:'🧠', cat:'verb'},
  {en:'think',  ro:'a gândi',    ph:'ΘINK',    e:'💭', cat:'verb'},
  {en:'see',    ro:'a vedea',    ph:'SII',     e:'👁️', cat:'verb'},
  {en:'come',   ro:'a veni',     ph:'CAM',     e:'🏃', cat:'verb'},
  {en:'want',   ro:'a vrea',     ph:'UONT',    e:'✨', cat:'verb'},
  {en:'look',   ro:'a privi',    ph:'LUK',     e:'👀', cat:'verb'},
  {en:'give',   ro:'a da',       ph:'GIV',     e:'🤝', cat:'verb'},
  {en:'find',   ro:'a găsi',     ph:'FAIND',   e:'🔍', cat:'verb'},
  {en:'tell',   ro:'a spune',    ph:'TEL',     e:'📢', cat:'verb'},
  {en:'ask',    ro:'a întreba',  ph:'ASK',     e:'🙋', cat:'verb'},
  {en:'work',   ro:'a lucra',    ph:'UORK',    e:'💼', cat:'verb'},
  {en:'feel',   ro:'a simți',    ph:'FIIL',    e:'💓', cat:'verb'},
  {en:'try',    ro:'a încerca',  ph:'TRAI',    e:'🎯', cat:'verb'},
  {en:'leave',  ro:'a pleca',    ph:'LIIV',    e:'🚪', cat:'verb'},
  {en:'call',   ro:'a suna',     ph:'COL',     e:'📞', cat:'verb'},
  {en:'show',   ro:'a arăta',    ph:'ȘOU',     e:'👆', cat:'verb'},
  {en:'hear',   ro:'a auzi',     ph:'HIR',     e:'👂', cat:'verb'},
  {en:'run',    ro:'a alerga',   ph:'RAN',     e:'🏃', cat:'verb'},
  {en:'live',   ro:'a locui',    ph:'LIV',     e:'🏠', cat:'verb'},
  {en:'play',   ro:'a se juca',  ph:'PLEI',    e:'🎮', cat:'verb'},
  {en:'sit',    ro:'a sta jos',  ph:'SIT',     e:'🪑', cat:'verb'},
  {en:'bring',  ro:'a aduce',    ph:'BRING',   e:'🎁', cat:'verb'},
  {en:'write',  ro:'a scrie',    ph:'RAIT',    e:'✍️', cat:'verb'},
  {en:'read',   ro:'a citi',     ph:'RIID',    e:'📖', cat:'verb'},
  {en:'speak',  ro:'a vorbi',    ph:'SPIIK',   e:'🗣️', cat:'verb'},
  {en:'listen', ro:'a asculta',  ph:'LISN',    e:'👂', cat:'verb'},
  {en:'learn',  ro:'a învăța',   ph:'LERN',    e:'🎓', cat:'verb'},
  {en:'study',  ro:'a studia',   ph:'STADI',   e:'📚', cat:'verb'},
  {en:'eat',    ro:'a mânca',    ph:'IIT',     e:'🍽️', cat:'verb'},
  {en:'drink',  ro:'a bea',      ph:'DRINK',   e:'🥤', cat:'verb'},
  {en:'sleep',  ro:'a dormi',    ph:'SLIIP',   e:'😴', cat:'verb'},
  {en:'buy',    ro:'a cumpăra',  ph:'BAI',     e:'🛍️', cat:'verb'},
  {en:'cook',   ro:'a găti',     ph:'KUK',     e:'👨‍🍳', cat:'verb'},
  {en:'watch',  ro:'a urmări',   ph:'UOCI',    e:'📺', cat:'verb'},
  {en:'like',   ro:'a-i plăcea', ph:'LAIK',    e:'❤️', cat:'verb'},
  {en:'love',   ro:'a iubi',     ph:'LAV',     e:'💕', cat:'verb'},
  {en:'visit',  ro:'a vizita',   ph:'VIZIT',   e:'🗺️', cat:'verb'},
  {en:'open',   ro:'a deschide', ph:'OUPEN',   e:'🔓', cat:'verb'},
  {en:'close',  ro:'a închide',  ph:'CLOUZ',   e:'🔒', cat:'verb'},
  {en:'start',  ro:'a începe',   ph:'START',   e:'▶️', cat:'verb'},
  {en:'stop',   ro:'a opri',     ph:'STOP',    e:'⏹️', cat:'verb'},
  {en:'help',   ro:'a ajuta',    ph:'HELP',    e:'🆘', cat:'verb'},
  {en:'need',   ro:'a avea nevoie',ph:'NIID',  e:'📌', cat:'verb'},

  // CASĂ
  {en:'House',    ro:'Casă',      ph:'HAUS',    e:'🏠', cat:'casă'},
  {en:'Room',     ro:'Cameră',    ph:'RUUM',    e:'🛋️', cat:'casă'},
  {en:'Door',     ro:'Ușă',       ph:'DOR',     e:'🚪', cat:'casă'},
  {en:'Window',   ro:'Fereastră', ph:'UINDOU',  e:'🪟', cat:'casă'},
  {en:'Kitchen',  ro:'Bucătărie', ph:'KICEN',   e:'🍳', cat:'casă'},
  {en:'Bathroom', ro:'Baie',      ph:'BAΘRUUM', e:'🛁', cat:'casă'},
  {en:'Bedroom',  ro:'Dormitor',  ph:'BEDRUUM', e:'🛏️', cat:'casă'},
  {en:'Table',    ro:'Masă',      ph:'TEIBL',   e:'🪑', cat:'casă'},
  {en:'Chair',    ro:'Scaun',     ph:'CEIR',    e:'🪑', cat:'casă'},
  {en:'Bed',      ro:'Pat',       ph:'BED',     e:'🛏️', cat:'casă'},
  {en:'Sofa',     ro:'Canapea',   ph:'SOUFA',   e:'🛋️', cat:'casă'},
  {en:'Lamp',     ro:'Lampă',     ph:'LAMP',    e:'💡', cat:'casă'},
  {en:'TV',       ro:'Televizor', ph:'TI-VII',  e:'📺', cat:'casă'},
  {en:'Phone',    ro:'Telefon',   ph:'FOUN',    e:'📱', cat:'casă'},
  {en:'Key',      ro:'Cheie',     ph:'KI',      e:'🔑', cat:'casă'},
  {en:'Garden',   ro:'Grădină',   ph:'GARDN',   e:'🌿', cat:'casă'},
  {en:'Stairs',   ro:'Scări',     ph:'STERZ',   e:'🪜', cat:'casă'},

  // FAMILIE
  {en:'Mother',      ro:'Mamă',     ph:'MAĐER',     e:'👩', cat:'familie'},
  {en:'Father',      ro:'Tată',     ph:'FAĐER',     e:'👨', cat:'familie'},
  {en:'Sister',      ro:'Soră',     ph:'SISTER',    e:'👧', cat:'familie'},
  {en:'Brother',     ro:'Frate',    ph:'BRAĐER',    e:'👦', cat:'familie'},
  {en:'Baby',        ro:'Bebeluș',  ph:'BEIBI',     e:'👶', cat:'familie'},
  {en:'Grandmother', ro:'Bunică',   ph:'GRANMAĐER', e:'👵', cat:'familie'},
  {en:'Grandfather', ro:'Bunic',    ph:'GRANFAĐER', e:'👴', cat:'familie'},
  {en:'Son',         ro:'Fiu',      ph:'SAN',       e:'👦', cat:'familie'},
  {en:'Daughter',    ro:'Fiică',    ph:'DOTER',     e:'👧', cat:'familie'},
  {en:'Husband',     ro:'Soț',      ph:'HAZBAND',   e:'👨', cat:'familie'},
  {en:'Wife',        ro:'Soție',    ph:'UAIF',      e:'👩', cat:'familie'},
  {en:'Friend',      ro:'Prieten',  ph:'FREND',     e:'🤝', cat:'familie'},
  {en:'Aunt',        ro:'Mătușă',   ph:'ANT',       e:'👩', cat:'familie'},
  {en:'Uncle',       ro:'Unchi',    ph:'ANKL',      e:'👨', cat:'familie'},
  {en:'Cousin',      ro:'Văr/Vară', ph:'KAZN',      e:'🧑', cat:'familie'},
  {en:'Child',       ro:'Copil',    ph:'CEAILD',    e:'🧒', cat:'familie'},
  {en:'Family',      ro:'Familie',  ph:'FAMILI',    e:'👨‍👩‍👧', cat:'familie'},

  // MÂNCARE
  {en:'Apple',   ro:'Măr',      ph:'APL',    e:'🍎', cat:'mâncare'},
  {en:'Bread',   ro:'Pâine',    ph:'BRED',   e:'🍞', cat:'mâncare'},
  {en:'Water',   ro:'Apă',      ph:'UOTER',  e:'💧', cat:'mâncare'},
  {en:'Milk',    ro:'Lapte',    ph:'MILK',   e:'🥛', cat:'mâncare'},
  {en:'Egg',     ro:'Ou',       ph:'EG',     e:'🥚', cat:'mâncare'},
  {en:'Cheese',  ro:'Brânză',   ph:'CIIZ',   e:'🧀', cat:'mâncare'},
  {en:'Chicken', ro:'Pui',      ph:'CIKEN',  e:'🍗', cat:'mâncare'},
  {en:'Rice',    ro:'Orez',     ph:'RAIS',   e:'🍚', cat:'mâncare'},
  {en:'Soup',    ro:'Supă',     ph:'SUUP',   e:'🍲', cat:'mâncare'},
  {en:'Pizza',   ro:'Pizza',    ph:'PITSA',  e:'🍕', cat:'mâncare'},
  {en:'Coffee',  ro:'Cafea',    ph:'COFI',   e:'☕', cat:'mâncare'},
  {en:'Tea',     ro:'Ceai',     ph:'TII',    e:'🍵', cat:'mâncare'},
  {en:'Juice',   ro:'Suc',      ph:'DJUS',   e:'🧃', cat:'mâncare'},
  {en:'Sugar',   ro:'Zahăr',    ph:'ȘUGAR',  e:'🍬', cat:'mâncare'},
  {en:'Salt',    ro:'Sare',     ph:'SOLT',   e:'🧂', cat:'mâncare'},
  {en:'Fish',    ro:'Pește',    ph:'FIȘ',    e:'🐟', cat:'mâncare'},
  {en:'Fruit',   ro:'Fruct',    ph:'FRUUT',  e:'🍓', cat:'mâncare'},

  // TRANSPORT
  {en:'Car',      ro:'Mașină',    ph:'KAR',      e:'🚗', cat:'transport'},
  {en:'Bus',      ro:'Autobuz',   ph:'BAS',      e:'🚌', cat:'transport'},
  {en:'Train',    ro:'Tren',      ph:'TREIN',    e:'🚂', cat:'transport'},
  {en:'Airplane', ro:'Avion',     ph:'AIRPLEIN', e:'✈️', cat:'transport'},
  {en:'Taxi',     ro:'Taxi',      ph:'TAKSI',    e:'🚕', cat:'transport'},
  {en:'Bicycle',  ro:'Bicicletă', ph:'BAISIKL',  e:'🚲', cat:'transport'},
  {en:'Street',   ro:'Stradă',    ph:'STRIIT',   e:'🛣️', cat:'transport'},
  {en:'Station',  ro:'Stație',    ph:'STEIȘEN',  e:'🏢', cat:'transport'},
  {en:'Airport',  ro:'Aeroport',  ph:'AIRPORT',  e:'🛫', cat:'transport'},
  {en:'Ticket',   ro:'Bilet',     ph:'TIKET',    e:'🎫', cat:'transport'},
  {en:'Left',     ro:'Stânga',    ph:'LEFT',     e:'⬅️', cat:'transport'},
  {en:'Right',    ro:'Dreapta',   ph:'RAIT',     e:'➡️', cat:'transport'},
  {en:'Straight', ro:'Înainte',   ph:'STREIT',   e:'⬆️', cat:'transport'},
  {en:'Stop',     ro:'Stop',      ph:'STOP',     e:'🛑', cat:'transport'},

  // MUNCĂ
  {en:'Work',     ro:'Muncă',          ph:'UORK',     e:'💼', cat:'muncă'},
  {en:'Office',   ro:'Birou',          ph:'OFIS',     e:'🏢', cat:'muncă'},
  {en:'Computer', ro:'Calculator',     ph:'KOMPUTER', e:'💻', cat:'muncă'},
  {en:'Meeting',  ro:'Întâlnire',      ph:'MIITING',  e:'👥', cat:'muncă'},
  {en:'Boss',     ro:'Șef',            ph:'BOS',      e:'👔', cat:'muncă'},
  {en:'Money',    ro:'Bani',           ph:'MANI',     e:'💰', cat:'muncă'},
  {en:'Job',      ro:'Serviciu',       ph:'DJOB',     e:'🔧', cat:'muncă'},
  {en:'Email',    ro:'Email',          ph:'I-MEIL',   e:'📧', cat:'muncă'},
  {en:'Team',     ro:'Echipă',         ph:'TIIM',     e:'👫', cat:'muncă'},
  {en:'Project',  ro:'Proiect',        ph:'PRODJEKT', e:'📊', cat:'muncă'},
  {en:'Salary',   ro:'Salariu',        ph:'SALERI',   e:'💵', cat:'muncă'},
  {en:'Holiday',  ro:'Vacanță',        ph:'HOLIDEI',  e:'🏖️', cat:'muncă'},
  {en:'Deadline', ro:'Termen limită',  ph:'DEDLAIN',  e:'⏰', cat:'muncă'},

  // CĂLĂTORII
  {en:'Hotel',      ro:'Hotel',       ph:'HOUTEL',    e:'🏨', cat:'călătorii'},
  {en:'Passport',   ro:'Pașaport',    ph:'PASSPORT',  e:'📘', cat:'călătorii'},
  {en:'Luggage',    ro:'Bagaj',       ph:'LAGIDJ',    e:'🧳', cat:'călătorii'},
  {en:'Beach',      ro:'Plajă',       ph:'BIICI',     e:'🏖️', cat:'călătorii'},
  {en:'Mountain',   ro:'Munte',       ph:'MAUNTIN',   e:'⛰️', cat:'călătorii'},
  {en:'City',       ro:'Oraș',        ph:'SITI',      e:'🏙️', cat:'călătorii'},
  {en:'Restaurant', ro:'Restaurant',  ph:'RESTORANT', e:'🍽️', cat:'călătorii'},
  {en:'Museum',     ro:'Muzeu',       ph:'MIUZIIM',   e:'🏛️', cat:'călătorii'},
  {en:'Camera',     ro:'Aparat foto', ph:'KAMERA',    e:'📷', cat:'călătorii'},
  {en:'Tour',       ro:'Tur',         ph:'TUR',       e:'🗺️', cat:'călătorii'},
  {en:'Visa',       ro:'Viză',        ph:'VIIZA',     e:'🪪', cat:'călătorii'},
  {en:'Guide',      ro:'Ghid',        ph:'GAID',      e:'🧑‍🏫', cat:'călătorii'},

  // ADJECTIVE
  {en:'Good',      ro:'Bun',        ph:'GUD',       e:'👍', cat:'adjectiv'},
  {en:'Bad',       ro:'Rău',        ph:'BAD',       e:'👎', cat:'adjectiv'},
  {en:'Big',       ro:'Mare',       ph:'BIG',       e:'🔵', cat:'adjectiv'},
  {en:'Small',     ro:'Mic',        ph:'SMOL',      e:'🔹', cat:'adjectiv'},
  {en:'New',       ro:'Nou',        ph:'NIUU',      e:'✨', cat:'adjectiv'},
  {en:'Old',       ro:'Vechi',      ph:'OLD',       e:'📜', cat:'adjectiv'},
  {en:'Happy',     ro:'Fericit',    ph:'HAPI',      e:'😊', cat:'adjectiv'},
  {en:'Sad',       ro:'Trist',      ph:'SAD',       e:'😢', cat:'adjectiv'},
  {en:'Fast',      ro:'Rapid',      ph:'FAST',      e:'⚡', cat:'adjectiv'},
  {en:'Slow',      ro:'Lent',       ph:'SLOU',      e:'🐢', cat:'adjectiv'},
  {en:'Hot',       ro:'Fierbinte',  ph:'HOT',       e:'🔥', cat:'adjectiv'},
  {en:'Cold',      ro:'Rece',       ph:'COLD',      e:'❄️', cat:'adjectiv'},
  {en:'Beautiful', ro:'Frumos',     ph:'BIUTIFUL',  e:'😍', cat:'adjectiv'},
  {en:'Easy',      ro:'Ușor',       ph:'IIZI',      e:'✅', cat:'adjectiv'},
  {en:'Hard',      ro:'Greu',       ph:'HARD',      e:'💪', cat:'adjectiv'},
  {en:'Tired',     ro:'Obosit',     ph:'TAIRD',     e:'😴', cat:'adjectiv'},
  {en:'Hungry',    ro:'Flămând',    ph:'HANGRI',    e:'🤤', cat:'adjectiv'},
  {en:'Important', ro:'Important',  ph:'IMPORTANT', e:'❗', cat:'adjectiv'},

  // TIMP
  {en:'Today',     ro:'Azi',            ph:'TUDEI',     e:'📅', cat:'timp'},
  {en:'Tomorrow',  ro:'Mâine',          ph:'TUMOROU',   e:'⏭️', cat:'timp'},
  {en:'Yesterday', ro:'Ieri',           ph:'IESTERDEI', e:'⏮️', cat:'timp'},
  {en:'Now',       ro:'Acum',           ph:'NAU',       e:'⚡', cat:'timp'},
  {en:'Always',    ro:'Mereu',          ph:'OLUEIZ',    e:'♾️', cat:'timp'},
  {en:'Never',     ro:'Niciodată',      ph:'NEVER',     e:'🚫', cat:'timp'},
  {en:'Sometimes', ro:'Uneori',         ph:'SAMTAIMZ',  e:'🔄', cat:'timp'},
  {en:'Every day', ro:'În fiecare zi',  ph:'EVRI DEI',  e:'☀️', cat:'timp'},
  {en:'Morning',   ro:'Dimineață',      ph:'MORNING',   e:'🌅', cat:'timp'},
  {en:'Evening',   ro:'Seară',          ph:'IIVNING',   e:'🌆', cat:'timp'},
  {en:'Night',     ro:'Noapte',         ph:'NAIT',      e:'🌙', cat:'timp'},
  {en:'Week',      ro:'Săptămână',      ph:'UIIK',      e:'📅', cat:'timp'},
  {en:'Month',     ro:'Lună',           ph:'MANΘ',      e:'📆', cat:'timp'},
  {en:'Year',      ro:'An',             ph:'IIR',       e:'🗓️', cat:'timp'},

  // SALUTĂRI
  {en:'Hello',         ro:'Bună',           ph:'HELOU',      e:'👋', cat:'salutări'},
  {en:'Goodbye',       ro:'La revedere',    ph:'GUDBAI',     e:'🙋', cat:'salutări'},
  {en:'Please',        ro:'Te rog',         ph:'PLIIZ',      e:'🙏', cat:'salutări'},
  {en:'Thank you',     ro:'Mulțumesc',      ph:'ΘENK IU',    e:'💙', cat:'salutări'},
  {en:'Sorry',         ro:'Îmi pare rău',   ph:'SORI',       e:'😔', cat:'salutări'},
  {en:'Yes',           ro:'Da',             ph:'IES',        e:'✅', cat:'salutări'},
  {en:'No',            ro:'Nu',             ph:'NOU',        e:'❌', cat:'salutări'},
  {en:'Excuse me',     ro:'Scuzați-mă',     ph:'EKSKIUUZ MI',e:'🤝', cat:'salutări'},
  {en:'Good morning',  ro:'Bună dimineața', ph:'GUD MORNING',e:'🌅', cat:'salutări'},
  {en:'Good night',    ro:'Noapte bună',    ph:'GUD NAIT',   e:'🌙', cat:'salutări'},
  {en:'How are you?',  ro:'Ce mai faci?',   ph:'HAU AR IU',  e:'🙂', cat:'salutări'},
  {en:'Nice to meet you', ro:'Îmi pare bine', ph:'NAIS TU MIIT IU', e:'🤝', cat:'salutări'},

  // CULORI
  {en:'Red',    ro:'Roșu',       ph:'RED',   e:'🔴', cat:'culoare', hex:'#e53935'},
  {en:'Blue',   ro:'Albastru',   ph:'BLUU',  e:'🔵', cat:'culoare', hex:'#1e88e5'},
  {en:'Green',  ro:'Verde',      ph:'GRIIN', e:'🟢', cat:'culoare', hex:'#43a047'},
  {en:'Yellow', ro:'Galben',     ph:'IELOU', e:'🟡', cat:'culoare', hex:'#fdd835'},
  {en:'Orange', ro:'Portocaliu', ph:'ORINJ', e:'🟠', cat:'culoare', hex:'#fb8c00'},
  {en:'Purple', ro:'Mov',        ph:'PERPL', e:'🟣', cat:'culoare', hex:'#8e24aa'},
  {en:'Pink',   ro:'Roz',        ph:'PINK',  e:'🩷', cat:'culoare', hex:'#e91e8c'},
  {en:'Black',  ro:'Negru',      ph:'BLAK',  e:'⬛', cat:'culoare', hex:'#212121'},
  {en:'White',  ro:'Alb',        ph:'UAIT',  e:'⬜', cat:'culoare', hex:'#eeeeee'},
  {en:'Brown',  ro:'Maro',       ph:'BRAUN', e:'🟫', cat:'culoare', hex:'#6d4c41'},
  {en:'Grey',   ro:'Gri',        ph:'GREI',  e:'🩶', cat:'culoare', hex:'#757575'},
  {en:'Gold',   ro:'Auriu',      ph:'GOLD',  e:'🥇', cat:'culoare', hex:'#ffc107'},

  // NUMERE
  {en:'One',       ro:'Unu',       ph:'UAN',     n:1,   cat:'număr'},
  {en:'Two',       ro:'Doi',       ph:'TUU',     n:2,   cat:'număr'},
  {en:'Three',     ro:'Trei',      ph:'ΘRII',    n:3,   cat:'număr'},
  {en:'Four',      ro:'Patru',     ph:'FOR',     n:4,   cat:'număr'},
  {en:'Five',      ro:'Cinci',     ph:'FAIV',    n:5,   cat:'număr'},
  {en:'Six',       ro:'Șase',      ph:'SIKS',    n:6,   cat:'număr'},
  {en:'Seven',     ro:'Șapte',     ph:'SEVN',    n:7,   cat:'număr'},
  {en:'Eight',     ro:'Opt',       ph:'EIT',     n:8,   cat:'număr'},
  {en:'Nine',      ro:'Nouă',      ph:'NAIN',    n:9,   cat:'număr'},
  {en:'Ten',       ro:'Zece',      ph:'TEN',     n:10,  cat:'număr'},
  {en:'Eleven',    ro:'Unsprezece',ph:'ILEVN',   n:11,  cat:'număr'},
  {en:'Twelve',    ro:'Doisprezece',ph:'TUELV',  n:12,  cat:'număr'},
  {en:'Thirteen',  ro:'Treisprezece',ph:'ΘERTIIN',n:13, cat:'număr'},
  {en:'Fourteen',  ro:'Paisprezece',ph:'FORTIIN', n:14, cat:'număr'},
  {en:'Fifteen',   ro:'Cincisprezece',ph:'FIFTIIN',n:15,cat:'număr'},
  {en:'Twenty',    ro:'Douăzeci',  ph:'TUENTI',  n:20,  cat:'număr'},
  {en:'Thirty',    ro:'Treizeci',  ph:'ΘERTI',   n:30,  cat:'număr'},
  {en:'Forty',     ro:'Patruzeci', ph:'FORTI',   n:40,  cat:'număr'},
  {en:'Fifty',     ro:'Cincizeci', ph:'FIFTI',   n:50,  cat:'număr'},
  {en:'Hundred',   ro:'O sută',    ph:'HANDRED', n:100, cat:'număr'},
];

// ── helpers ──────────────────────────────────────────────────
const DICT = {
  all: DICT_WORDS,
  by: cat => DICT_WORDS.filter(w => w.cat === cat),
  search: q => {
    const lq = q.toLowerCase();
    return DICT_WORDS.filter(w =>
      w.en.toLowerCase().includes(lq) || w.ro.toLowerCase().includes(lq)
    );
  },
  categories: [...new Set(DICT_WORDS.map(w => w.cat))],
};
